# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Denghong Yan 's Blog
subtitle: ''
description: 'Welcome to my blog where I share my thoughts on technology, programming, and everything in between.'
keywords:
author: Denghong Yan
language: en
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://skyxv.github.io/blog
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''


theme_config:
  # cactus
  # google_analytics:
  #   enabled: true
  #   id: G-4F49TZRQJT
  
  # nav:
  #   home: /
  #   articles: /archives/
  #   about: /about/

  # projects_url: http://github.com/skyxv

  # social_links:
  #   -
  #     icon: github
  #     link: http://github.com/skyxv
  #   -
  #     icon: mail
  #     link: mailto:vincentyim888@gmail.com

  # copyright:
  #   start_year: 2017
  #   end_year:

  # highlight: agate

  # logo:
  #   enabled: true
  #   width: 50
  #   height: 50
  #   url: /imgs/android-chrome-512x512.png
  #   gravatar: false
  #   grayout: true

  # favicon:
  #   desktop:
  #     url: /imgs/favicon.ico
  #     gravatar: false
  #   android:
  #     url: /imgs/android-chrome-192x192.png
  #     gravatar: false
  #   apple:
  #     url: /imgs/apple-touch-icon.png
  #     gravatar: false

  # ascent
  # menu:
  #   Home: /
  #   Archives: /archives/
  #   About: /about/
  #   Github: https://github.com/skyxv
  
  # google_analytics:
  #   enabled: true
  #   acct: G-4F49TZRQJT
  # favicon: /imgs/favicon.ico

  # maupassant
  # gitalk: ## See: https://github.com/gitalk/gitalk
  #   enable: true ## If you want to use Gitment comment system please set the value to true.
  #   owner: skyxv ## Your GitHub ID, e.g. username
  #   repo: blog ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  #   client_id: e84a5529741e575a2d7a ## GitHub client ID, e.g. 75752dafe7907a897619
  #   client_secret: a85723de25f3609c54f25af29d8ff8239917e478 ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  #   admin: skyxv ## Github repo owner and collaborators, only these guys can initialize github issues.
  # self_search: false
  # google_analytics: G-4F49TZRQJT
  # wordcount: false

  ### next
  favicon:
    small: /imgs/favicon.ico
    medium: imgs/android-chrome-192x192.png
    apple_touch_icon: /imgs/apple-touch-icon.png
    safari_pinned_tab: /imgs/android-chrome-512x512.png
  # scheme: Muse
  scheme: Mist
  # scheme: Pisces
  # scheme: Gemini

  # Dark Mode
  darkmode: true


  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimiter is the target link, value after `||` delimiter is the name of Font Awesome icon.
  # When running the site in a subdirectory (e.g. yoursite.com/blog), remove the leading slash from link value (/archives -> archives).
  # External url should start with http:// or https://
  menu:
    home: / || fa fa-home
    about: /about/ || fa fa-user
    #tags: /tags/ || fa fa-tags
    #categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
  
  avatar:
    # Replace the default image and set the url here.
    url: /imgs/android-chrome-512x512.png #/images/avatar.gif
    # If true, the avatar will be dispalyed in circle.
    rounded: false
    # If true, the avatar will be rotated with the cursor.
    rotated: false

  social:
    GitHub: https://github.com/skyxv || fab fa-github
    E-Mail: mailto:vincentyim888@gmail.com || fa fa-envelope

  comments:
    # Available values: tabs | buttons
    style: tabs
    # Choose a comment system to be displayed by default.
    # Available values: changyan | disqus | disqusjs | gitalk | livere | valine
    active: gitalk
    # Setting `true` means remembering the comment system selected by the visitor.
    storage: true
    # Lazyload all comment systems.
    lazyload: false
    # Modify texts or order for any navs, here are some examples.
    nav:
      #disqus:
      #  text: Load Disqus
      #  order: -1
      gitalk:
       order: -1
  gitalk:
    enable: true
    github_id: skyxv # GitHub repo owner
    repo: blog # Repository name to store issues
    client_id: e84a5529741e575a2d7a # GitHub Application Client ID
    client_secret: a85723de25f3609c54f25af29d8ff8239917e478 # GitHub Application Client Secret
    admin_user: skyxv # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
    distraction_free_mode: true # Facebook-like distraction free mode
    # Gitalk's display language depends on user's browser or system environment
    # If you want everyone visiting your site to see a uniform language, you can set a force language value
    # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
    language:
